---
abstract: "Simple 'sparkline' widget implementation"
author:
  - 'Tom Molesworth <cpan@entitymodel.com>'
build_requires:
  IO::Handle: 0
  IPC::Open3: 0
  Test::CheckDeps: 0.006
  Test::More: 0.98
  perl: 5.010001
configure_requires:
  ExtUtils::MakeMaker: 6.48
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tickit-Widget-SparkLine
requires:
  Tickit: 0.33
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Tickit-Widget-SparkLine
  homepage: http://search.cpan.org/dist/Tickit-Widget-SparkLine/
version: 0.102
